name: Test Repo A (Dispatcher)

on:
  workflow_dispatch:

jobs:
  dispatch:
    environment: dev
    name: Dispatch
    env:
      PACKAGES_TO_UPGRADE: ${{ needs.run_publish.outputs.packages }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ['grupoboticario/prodfin-programa-facilita-testes']
    timeout-minutes: 8
    steps:
      - name: Dispatch to workflows
        run: |
            curl -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: token ${{ secrets.TOKEN_OTHER_REPO }}" \
            --request POST \
            --data '{"event_type": "Standard", "client_payload": { "mooz": "true", "bank": "true", "provider": "false" }}' https://api.github.com/repos/${{ matrix.repo }}/dispatches
